# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180905_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='original_photo',
            field=models.ImageField(upload_to=b'original/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=b'photo/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='thumbs',
            field=models.ImageField(upload_to=b'thumbs/'),
        ),
    ]
