# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180905_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='height',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='photos',
            name='width',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
